name: Deploy site to Cloudflare Workers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare Worker
    defaults:
      run:
        working-directory: ./edge-worker-cloudflare
    steps:
      - uses: actions/checkout@v3
      - name: install wrangler
        run: 'yarn global add wrangler'
      - name: install dependencies
        run: 'yarn install'
      - name: deploy cloudflare
        run: 'yarn deploy'
        env:
          CLOUDFLARE_API_TOKEN: 'keg3T5RgXjyvUbds_ECMfgP29IYfNFOlC44DB3p4'
