name: Deploy site to Cloudflare Workers

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare Worker
    defaults:
      run:
        working-directory: ./edge-worker-cloudflare
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: 'yarn install'
      - name: Publish app
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: 'keg3T5RgXjyvUbds_ECMfgP29IYfNFOlC44DB3p4'
