name: Deploy site to Cloudflare Workers

on: [push]

jobs:
  deploy-main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
          uses: borales/actions-yarn@v4
          with:
            cmd: install

      - name: Publish to Cloudflare Workers Sites
        run: deploy
        env:
          CF_API_TOKEN: keg3T5RgXjyvUbds_ECMfgP29IYfNFOlC44DB3p4
